.TH "/home/ly/admin-linux/admin/__init__.py" 3 "Tue Sep 9 2014" "Version 0.0.0" "zl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ly/admin-linux/admin/__init__.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBadmin\&.ConfigFile\fP"
.br
.RI "\fIConfiguration file\&. \fP"
.ti -1c
.RI "class \fBadmin\&.AdminTestCase\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBadmin\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBadmin\&.error\fP"
.br
.RI "\fIPrint error messages\&. \fP"
.ti -1c
.RI "def \fBadmin\&.debug\fP"
.br
.RI "\fIPrint debugging message\&. \fP"
.ti -1c
.RI "def \fBadmin\&.update_seq_type\fP"
.br
.RI "\fIUpdate type of all elements in specific sequence\&. \fP"
.ti -1c
.RI "def \fBadmin\&.shell\fP"
.br
.RI "\fIRun shell commandi without output\&. \fP"
.ti -1c
.RI "def \fBadmin\&.force_remove\fP"
.br
.RI "\fICommand \fCrm -f\fP\&. \fP"
.ti -1c
.RI "def \fBadmin\&.eintr_retry\fP"
.br
.RI "\fIRestart a system call interrupted by \fCEINTR\fP\&. \fP"
.ti -1c
.RI "def \fBadmin\&.decode_version\fP"
.br
.RI "\fIDecode version information string\&. \fP"
.ti -1c
.RI "def \fBadmin\&.match_version\fP"
.br
.RI "\fIMatch the specific version\&. \fP"
.ti -1c
.RI "def \fBadmin\&.read_lines\fP"
.br
.RI "\fIRead specific line(s) with line number(s)\&. \fP"
.ti -1c
.RI "def \fBadmin\&.cpu_cores\fP"
.br
.ti -1c
.RI "def \fBadmin\&.run_uwsgi\fP"
.br
.RI "\fIRun (or Reload) uWSGI server\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBadmin\&.Version\fP = namedtuple('Version', 'major, minor, patch')"
.br
.ti -1c
.RI "string \fBadmin\&.www_root\fP = '/var/spool/www'"
.br
.ti -1c
.RI "string \fBadmin\&.uwsgi_log_root\fP = '/var/log/uwsgi'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for zl from the source code\&.
