.TH "admin/__init__.py" 3 "Wed Aug 27 2014" "Version 0.0.0" "admin-linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
admin/__init__.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBadmin\&.ConfigFile\fP"
.br
.RI "\fIConfiguration file\&. \fP"
.ti -1c
.RI "class \fBadmin\&.AdminTestCase\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBadmin\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBadmin\&.error\fP"
.br
.RI "\fIPrint error messages\&. \fP"
.ti -1c
.RI "def \fBadmin\&.debug\fP"
.br
.RI "\fIPrint debugging message\&. \fP"
.ti -1c
.RI "def \fBadmin\&.update_seq_type\fP"
.br
.RI "\fIUpdate type of all elements in specific sequence\&. \fP"
.ti -1c
.RI "def \fBadmin\&.force_remove\fP"
.br
.RI "\fILike command \fCrm -f\fP\&. \fP"
.ti -1c
.RI "def \fBadmin\&.decode_version\fP"
.br
.RI "\fIDecode version information string\&. \fP"
.ti -1c
.RI "def \fBadmin\&.match_version\fP"
.br
.RI "\fIMatch the specific version\&. \fP"
.ti -1c
.RI "def \fBadmin\&.read_lines\fP"
.br
.RI "\fIRead specific line(s) with line number(s)\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBadmin\&.Version\fP = namedtuple('Version', 'major, minor, patch')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for admin-linux from the source code\&.
