.TH "_cookbook.network" 3 "Wed Sep 17 2014" "Version 0.0.0" "admin-linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_cookbook.network \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMyTCPServer\fP"
.br
.ti -1c
.RI "class \fBMyUDPServer\fP"
.br
.ti -1c
.RI "class \fBMyTCPHandler\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fB_eintr_retry\fP"
.br
.ti -1c
.RI "def \fBtcp_client\fP"
.br
.ti -1c
.RI "def \fBudp_client\fP"
.br
.ti -1c
.RI "def \fBtcp_server\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBsrv\fP = \fBMyTCPServer\fP(('', 10000))"
.br
.ti -1c
.RI "tuple \fBsrv_addr\fP = ('localhost', 10000)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def _cookbook\&.network\&._eintr_retry (func, args)\fC [private]\fP"

.PP
.nf
restart a system call interrupted by EINTR.

@param func system call
@param args arguments of system call
@return results of system call
@exception OSError
@exception select.error

.fi
.PP
 
.PP
Definition at line 75 of file network\&.py\&.
.SS "def _cookbook\&.network\&.tcp_client (addr, buf_size = \fC1024\fP, reconn = \fC3\fP)"

.PP
.nf
TCP Client.

@param addr server address, 2-tuple of (host, port)
@param buf_size receiving buffer size
@param reconn re-connect times
@exception socket.error

.fi
.PP
 
.PP
Definition at line 320 of file network\&.py\&.
.SS "def _cookbook\&.network\&.tcp_server (host, port)"

.PP
.nf
SocketServer.TCPServer.

@param host host name or IP of server
@param port port number of server

.fi
.PP
 
.PP
Definition at line 400 of file network\&.py\&.
.SS "def _cookbook\&.network\&.udp_client (addr, buf_size = \fC1024\fP)"

.PP
.nf
UDP Client.

@param addr server address, 2-tuple of (host, port)
@param buf_size receiving buffer size
@exception socket.error

.fi
.PP
 
.PP
Definition at line 366 of file network\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "tuple _cookbook\&.network\&.srv = \fBMyTCPServer\fP(('', 10000))"

.PP
Definition at line 415 of file network\&.py\&.
.SS "tuple _cookbook\&.network\&.srv_addr = ('localhost', 10000)"

.PP
Definition at line 420 of file network\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for admin-linux from the source code\&.
