.TH "_cookbook.OOP.A" 3 "Wed Sep 17 2014" "Version 0.0.0" "admin-linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_cookbook.OOP.A \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.PP
Inherited by \fB_cookbook\&.OOP\&.B\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBpublic_instance_method\fP"
.br
.ti -1c
.RI "def \fBclass_method\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBstatic_method\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBpublic_instance_attribute\fP"
.br
.ti -1c
.RI "\fBprivate_instance_attribute\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnum_of_instances\fP = 0"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "def \fB_private_instance_method\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A class.

    >>> assert isinstance(A(), A)
.fi
.PP
 
.PP
Definition at line 59 of file OOP\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def _cookbook\&.OOP\&.A\&.__init__ (self, a1 = \fCNone\fP, a2 = \fCNone\fP)"

.PP
Definition at line 71 of file OOP\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def _cookbook\&.OOP\&.A\&._private_instance_method (self)\fC [private]\fP"

.PP
Definition at line 83 of file OOP\&.py\&.
.SS "def _cookbook\&.OOP\&.A\&.class_method (cls)"

.PP
Definition at line 93 of file OOP\&.py\&.
.SS "def _cookbook\&.OOP\&.A\&.public_instance_method (self)"

.PP
Definition at line 77 of file OOP\&.py\&.
.SS "def _cookbook\&.OOP\&.A\&.static_method ()\fC [static]\fP"

.PP
Definition at line 88 of file OOP\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "int _cookbook\&.OOP\&.A\&.num_of_instances = 0\fC [static]\fP"

.PP
Definition at line 69 of file OOP\&.py\&.
.SS "_cookbook\&.OOP\&.A\&.private_instance_attribute"

.PP
Definition at line 74 of file OOP\&.py\&.
.SS "_cookbook\&.OOP\&.A\&.public_instance_attribute"

.PP
Definition at line 73 of file OOP\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for admin-linux from the source code\&.
