.TH "_cookbook.thread.semaphore" 3 "Wed Sep 17 2014" "Version 0.0.0" "admin-linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_cookbook.thread.semaphore \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBProducer\fP"
.br
.ti -1c
.RI "class \fBCusumer\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBtest_semaphore\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBshare\fP = []"
.br
.ti -1c
.RI "int \fBMAX_COUNTS\fP = 5"
.br
.ti -1c
.RI "tuple \fBsemaphore\fP = threading\&.BoundedSemaphore(\fBMAX_COUNTS\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def _cookbook\&.thread\&.semaphore\&.test_semaphore ()"

.PP
.nf
Test multithreading using Semaphore.
.fi
.PP
 
.PP
Definition at line 76 of file semaphore\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "int _cookbook\&.thread\&.semaphore\&.MAX_COUNTS = 5"

.PP
Definition at line 38 of file semaphore\&.py\&.
.SS "tuple _cookbook\&.thread\&.semaphore\&.semaphore = threading\&.BoundedSemaphore(\fBMAX_COUNTS\fP)"

.PP
Definition at line 39 of file semaphore\&.py\&.
.SS "list _cookbook\&.thread\&.semaphore\&.share = []"

.PP
Definition at line 37 of file semaphore\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for admin-linux from the source code\&.
