.TH "_cookbook.sort" 3 "Wed Sep 17 2014" "Version 0.0.0" "admin-linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_cookbook.sort \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBApp\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBd\fP"
.br
.ti -1c
.RI "list \fBapps\fP = [\fBApp\fP(1), \fBApp\fP(2), \fBApp\fP(3)]"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "list _cookbook\&.sort\&.apps = [\fBApp\fP(1), \fBApp\fP(2), \fBApp\fP(3)]"

.PP
Definition at line 97 of file sort\&.py\&.
.SS "list _cookbook\&.sort\&.d"
\fBInitial value:\fP
.PP
.nf
1 = [
2     {'name': 'b', 'value': 3},
3     {'name': 'a', 'value': 2},
4     {'name': 'c', 'value': 1}
5 ]
.fi
.PP
Definition at line 57 of file sort\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for admin-linux from the source code\&.
