.TH "_cookbook.format" 3 "Wed Sep 17 2014" "Version 0.0.0" "admin-linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_cookbook.format \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBtest_float_format\fP"
.br
.ti -1c
.RI "def \fBtest_int_format\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def _cookbook\&.format\&.test_float_format ()"

.PP
Definition at line 23 of file format\&.py\&.
.SS "def _cookbook\&.format\&.test_int_format ()"

.PP
Definition at line 35 of file format\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for admin-linux from the source code\&.
