.TH "_cookbook.unpack_iterable" 3 "Wed Sep 17 2014" "Version 0.0.0" "admin-linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_cookbook.unpack_iterable \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBseq\fP = [1, 2, 3, 4, 5]"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "list _cookbook\&.unpack_iterable\&.seq = [1, 2, 3, 4, 5]"

.PP
Definition at line 25 of file unpack_iterable\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for admin-linux from the source code\&.
