.TH "_cookbook.OOP.B" 3 "Wed Sep 17 2014" "Version 0.0.0" "admin-linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_cookbook.OOP.B \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fB_cookbook\&.OOP\&.A\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBpublic_instance_method\fP"
.br
.ti -1c
.RI "def \fBnew_method\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBb\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
.nf
Subclass of A.

    >>> assert issubclass(B ,A)
.fi
.PP
 
.PP
Definition at line 97 of file OOP\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def _cookbook\&.OOP\&.B\&.__init__ (self, b, a1 = \fCNone\fP, a2 = \fCNone\fP)"

.PP
Definition at line 104 of file OOP\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def _cookbook\&.OOP\&.B\&.new_method (self)"

.PP
Definition at line 113 of file OOP\&.py\&.
.SS "def _cookbook\&.OOP\&.B\&.public_instance_method (self)"

.PP
Definition at line 109 of file OOP\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "_cookbook\&.OOP\&.B\&.b"

.PP
Definition at line 106 of file OOP\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for admin-linux from the source code\&.
