.TH "_cookbook.thread._queue.Cusumer" 3 "Wed Sep 17 2014" "Version 0.0.0" "admin-linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_cookbook.thread._queue.Cusumer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Thread\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBrun\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fB_times\fP"
.br
.ti -1c
.RI "\fB_item\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 52 of file _queue\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def _cookbook\&.thread\&._queue\&.Cusumer\&.__init__ (self, times = \fC1\fP)"

.PP
Definition at line 53 of file _queue\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def _cookbook\&.thread\&._queue\&.Cusumer\&.run (self)"

.PP
Definition at line 58 of file _queue\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "_cookbook\&.thread\&._queue\&.Cusumer\&._item\fC [private]\fP"

.PP
Definition at line 56 of file _queue\&.py\&.
.SS "_cookbook\&.thread\&._queue\&.Cusumer\&._times\fC [private]\fP"

.PP
Definition at line 55 of file _queue\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for admin-linux from the source code\&.
