.TH "_cookbook.network.MyUDPServer" 3 "Wed Sep 17 2014" "Version 0.0.0" "admin-linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_cookbook.network.MyUDPServer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBserve_forever\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBserver_address\fP"
.br
.ti -1c
.RI "\fBsocket\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBaddress_family\fP = socket\&.AF_INET"
.br
.ti -1c
.RI "\fBsocket_type\fP = socket\&.SOCK_DGRAM"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fB_buf_size\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Synchronous UDP Server (Only IPv4).

.fi
.PP
 
.PP
Definition at line 272 of file network\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def _cookbook\&.network\&.MyUDPServer\&.__init__ (self, address, buf_size = \fC1024\fP)"

.PP
.nf
Create an instance of UDP server.

@param address server address, 2-tuple (host, port)
@param buf_size receiving buffer size
@exception socket.error

.fi
.PP
 
.PP
Definition at line 278 of file network\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def _cookbook\&.network\&.MyUDPServer\&.serve_forever (self)"

.PP
.nf
Run server.

.fi
.PP
 
.PP
Definition at line 295 of file network\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "_cookbook\&.network\&.MyUDPServer\&._buf_size\fC [private]\fP"

.PP
Definition at line 286 of file network\&.py\&.
.SS "_cookbook\&.network\&.MyUDPServer\&.address_family = socket\&.AF_INET\fC [static]\fP"

.PP
Definition at line 275 of file network\&.py\&.
.SS "_cookbook\&.network\&.MyUDPServer\&.server_address"

.PP
Definition at line 285 of file network\&.py\&.
.SS "_cookbook\&.network\&.MyUDPServer\&.socket"

.PP
Definition at line 289 of file network\&.py\&.
.SS "_cookbook\&.network\&.MyUDPServer\&.socket_type = socket\&.SOCK_DGRAM\fC [static]\fP"

.PP
Definition at line 276 of file network\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for admin-linux from the source code\&.
