.TH "_cookbook.OOP" 3 "Wed Sep 17 2014" "Version 0.0.0" "admin-linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_cookbook.OOP \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBA\fP"
.br
.ti -1c
.RI "class \fBB\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for admin-linux from the source code\&.
