.TH "_cookbook.thread.my_queue" 3 "Wed Sep 17 2014" "Version 0.0.0" "admin-linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_cookbook.thread.my_queue \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMyQueue\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBtest\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB_times\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def _cookbook\&.thread\&.my_queue\&.test ()"

.PP
Definition at line 188 of file my_queue\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "_cookbook\&.thread\&.my_queue\&._times"

.PP
Definition at line 197 of file my_queue\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for admin-linux from the source code\&.
