.TH "_cookbook.network.MyTCPHandler" 3 "Wed Sep 17 2014" "Version 0.0.0" "admin-linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_cookbook.network.MyTCPHandler \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits StreamRequestHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBhandle\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
TCP handler by framework "SocketServer"

.fi
.PP
 
.PP
Definition at line 388 of file network\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def _cookbook\&.network\&.MyTCPHandler\&.handle (self)"

.PP
Definition at line 391 of file network\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "_cookbook\&.network\&.MyTCPHandler\&.data"

.PP
Definition at line 395 of file network\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for admin-linux from the source code\&.
