.TH "_cookbook.context_manager.MyContextManagerWithDecorator" 3 "Wed Sep 17 2014" "Version 0.0.0" "admin-linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_cookbook.context_manager.MyContextManagerWithDecorator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBclose\fP"
.br
.ti -1c
.RI "def \fBdo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 77 of file context_manager\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def _cookbook\&.context_manager\&.MyContextManagerWithDecorator\&.__init__ (self, ok = \fCTrue\fP)"

.PP
Definition at line 78 of file context_manager\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def _cookbook\&.context_manager\&.MyContextManagerWithDecorator\&.close (self)"

.PP
Definition at line 86 of file context_manager\&.py\&.
.SS "def _cookbook\&.context_manager\&.MyContextManagerWithDecorator\&.do (self, ok = \fCTrue\fP)"

.PP
Definition at line 90 of file context_manager\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for admin-linux from the source code\&.
