.TH "_cookbook.find" 3 "Wed Sep 17 2014" "Version 0.0.0" "admin-linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_cookbook.find \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBseq\fP = [1, 8, 2, 23, 7, -2, 18, 23, 42, 37, 2]"
.br
.ti -1c
.RI "list \fBlist_of_dict\fP"
.br
.ti -1c
.RI "dictionary \fBd\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "dictionary _cookbook\&.find\&.d"
\fBInitial value:\fP
.PP
.nf
1 = {
2         'IBM': 91\&.1,
3         'AAPL': 543\&.22,
4         'FB': 21\&.09
5 }
.fi
.PP
Definition at line 61 of file find\&.py\&.
.SS "list _cookbook\&.find\&.list_of_dict"
\fBInitial value:\fP
.PP
.nf
1 = [
2         {'name': 'IBM', 'shares': 100, 'price': 91\&.1},
3         {'name': 'AAPL', 'shares': 50, 'price': 543\&.22},
4         {'name': 'FB', 'shares': 200, 'price': 21\&.09},
5         {'name': 'HPQ', 'shares': 35, 'price': 31\&.74},
6         {'name': 'YHOO', 'shares': 45, 'price': 16\&.35},
7         {'name':'ACME', 'shares': 75, 'price': 115\&.65}
8 ]
.fi
.PP
Definition at line 45 of file find\&.py\&.
.SS "list _cookbook\&.find\&.seq = [1, 8, 2, 23, 7, -2, 18, 23, 42, 37, 2]"

.PP
Definition at line 39 of file find\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for admin-linux from the source code\&.
