.TH "_cookbook/_doctest.py" 3 "Wed Sep 17 2014" "Version 0.0.0" "admin-linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_cookbook/_doctest.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fB_cookbook\&._doctest\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fB_cookbook\&._doctest\&.func_1\fP"
.br
.ti -1c
.RI "def \fB_cookbook\&._doctest\&.func_2\fP"
.br
.ti -1c
.RI "def \fB_cookbook\&._doctest\&.func_3\fP"
.br
.ti -1c
.RI "def \fB_cookbook\&._doctest\&.func_4\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for admin-linux from the source code\&.
