.TH "_cookbook Directory Reference" 3 "Wed Sep 17 2014" "Version 0.0.0" "admin-linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_cookbook Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBthread\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB__init__\&.py\fP"
.br
.ti -1c
.RI "file \fB_doctest\&.py\fP"
.br
.ti -1c
.RI "file \fB_unittest\&.py\fP"
.br
.ti -1c
.RI "file \fBcontext_manager\&.py\fP"
.br
.ti -1c
.RI "file \fBfile\&.py\fP"
.br
.ti -1c
.RI "file \fBfind\&.py\fP"
.br
.ti -1c
.RI "file \fBformat\&.py\fP"
.br
.ti -1c
.RI "file \fBfunc_param\&.py\fP"
.br
.ti -1c
.RI "file \fBloop\&.py\fP"
.br
.ti -1c
.RI "file \fBmy_pyunit\&.py\fP"
.br
.ti -1c
.RI "file \fBnetwork\&.py\fP"
.br
.ti -1c
.RI "file \fBOOP\&.py\fP"
.br
.ti -1c
.RI "file \fBsort\&.py\fP"
.br
.ti -1c
.RI "file \fBtext_pattern\&.py\fP"
.br
.ti -1c
.RI "file \fBunpack_iterable\&.py\fP"
.br
.in -1c
