.TH "_cookbook/thread/_queue.py" 3 "Wed Sep 17 2014" "Version 0.0.0" "admin-linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_cookbook/thread/_queue.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_cookbook\&.thread\&._queue\&.Producer\fP"
.br
.ti -1c
.RI "class \fB_cookbook\&.thread\&._queue\&.Cusumer\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fB_cookbook\&.thread\&._queue\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fB_cookbook\&.thread\&._queue\&.test_queue\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fB_cookbook\&.thread\&._queue\&.q\fP = queue\&.Queue(maxsize=10)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for admin-linux from the source code\&.
