.TH "admin.ConfigFile" 3 "Wed Sep 17 2014" "Version 0.0.0" "admin-linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
admin.ConfigFile \- 
.PP
Configuration file\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIParse configuration file\&. \fP"
.ti -1c
.RI "def \fBget\fP"
.br
.RI "\fIGet value of specific option\&. \fP"
.ti -1c
.RI "def \fBset\fP"
.br
.RI "\fISet value of specific option\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fB_config_file\fP"
.br
.ti -1c
.RI "\fB_sep\fP"
.br
.ti -1c
.RI "\fB_comments\fP"
.br
.ti -1c
.RI "\fB_config\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Configuration file\&. 


.SS "Usage"
.PP
.PP
.nf
\fC
     import os
     import sys
     import admin\fP
.fi
.PP
.PP
.PP
.nf
\fC     configs = {'PROJECT_NAME': '"AAA"',
           'PROJECT_NUMBER': '1\&.2\&.3'}
     try:
         with open(os\&.path\&.join(os\&.getcwd(), 'Doxyfile'), 'r+') as f:
             config_file = \fBadmin\&.ConfigFile(f)\fP
             config_file\&.set(configs)
         except IOError as e:
             print('error', file=sys\&.stderr)
 \fP
.fi
.PP
 
.PP
Definition at line 868 of file admin\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def admin\&.ConfigFile\&.__init__ (self, config_file, sep = \fC'='\fP, comments = \fC'#'\fP)"

.PP
Parse configuration file\&. 
.PP
\fBParameters:\fP
.RS 4
\fIconfig_file\fP configuration file object 
.br
\fIsep\fP separator for option/value pair 
.br
\fIcomments\fP comments leading character 
.RE
.PP

.PP
Definition at line 875 of file admin\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def admin\&.ConfigFile\&.get (self, option)"

.PP
Get value of specific option\&. 
.PP
\fBParameters:\fP
.RS 4
\fIoption\fP option name 
.RE
.PP
\fBReturns:\fP
.RS 4
option value 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIKeyError\fP - no optinon exists 
.RE
.PP

.PP
Definition at line 895 of file admin\&.py\&.
.SS "def admin\&.ConfigFile\&.set (self, pairs)"

.PP
Set value of specific option\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpairs\fP Pairs of option name-value\&. 
.RE
.PP

.PP
Definition at line 902 of file admin\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "admin\&.ConfigFile\&._comments\fC [private]\fP"

.PP
Definition at line 878 of file admin\&.py\&.
.SS "admin\&.ConfigFile\&._config\fC [private]\fP"

.PP
Definition at line 879 of file admin\&.py\&.
.SS "admin\&.ConfigFile\&._config_file\fC [private]\fP"

.PP
Definition at line 876 of file admin\&.py\&.
.SS "admin\&.ConfigFile\&._sep\fC [private]\fP"

.PP
Definition at line 877 of file admin\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for admin-linux from the source code\&.
