.TH "admin.build" 3 "Wed Sep 17 2014" "Version 0.0.0" "admin-linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
admin.build \- 
.PP
Build tools\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBdecode_version\fP"
.br
.RI "\fIDecode version information string\&. \fP"
.ti -1c
.RI "def \fBmatch_version\fP"
.br
.RI "\fIMatch the specific version\&. \fP"
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBdoxygen\fP"
.br
.RI "\fIGenerate documentation for codes under Git by Doxygen\&. \fP"
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "tuple \fBVersion\fP = namedtuple('Version', 'major, minor, patch')"
.br
.in -1c
.SH "Detailed Description"
.PP 
Build tools\&. 

This module contains functions and classes for versions, including:
.PP
.IP "\(bu" 2
Version
.IP "\(bu" 2
\fBdecode_version()\fP, \fBmatch_version()\fP 
.PP

.PP
Definition at line 265 of file admin\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def admin\&.build\&.decode_version (cls, version_info, prefix = \fC''\fP)"

.PP
Decode version information string\&. 
.PP
\fBParameters:\fP
.RS 4
\fIversion_info\fP version information string (e\&.g\&. Python 3\&.4\&.1) 
.br
\fIprefix\fP prefix string of version 
.RE
.PP
\fBReturns:\fP
.RS 4
Version named-tuple 
.RE
.PP

.PP
Definition at line 275 of file admin\&.py\&.
.SS "def admin\&.build\&.doxygen (path, doxyfile = \fC'Doxyfile\&.in'\fP)\fC [static]\fP"

.PP
Generate documentation for codes under Git by Doxygen\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP project path 
.br
\fIdoxyfile\fP name of Doxygen configuration file 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIsubprocess\&.CalledProcessError\fP 
.br
\fIIOError\fP 
.RE
.PP
\fBSee Also:\fP
.RS 4
http://www.stack.nl/~dimitri/doxygen/manual/ 
.RE
.PP
\fBSince:\fP
.RS 4
Doxygen 1\&.8\&.6 
.RE
.PP

.PP
Definition at line 317 of file admin\&.py\&.
.SS "def admin\&.build\&.match_version (cls, v, match)"

.PP
Match the specific version\&. 
.PP
\fBParameters:\fP
.RS 4
\fIv\fP Version named-tuple 
.br
\fImatch\fP version string (e\&.g\&. 1\&.2\&.3) 
.RE
.PP
\fBReturns:\fP
.RS 4
True if match 
.RE
.PP

.PP
Definition at line 295 of file admin\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "tuple admin\&.build\&.Version = namedtuple('Version', 'major, minor, patch')\fC [static]\fP"

.PP
Definition at line 267 of file admin\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for admin-linux from the source code\&.
