.TH "admin.AdminError" 3 "Thu Sep 18 2014" "Version 0.0.0" "admin-linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
admin.AdminError \- 
.PP
admin error  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fB__str__\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBerror\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
admin error 
.PP
Definition at line 44 of file admin\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def admin\&.AdminError\&.__init__ (self, e)"

.PP
Definition at line 45 of file admin\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def admin\&.AdminError\&.__str__ (self)"

.PP
Definition at line 49 of file admin\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "admin\&.AdminError\&.error"

.PP
Definition at line 46 of file admin\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for admin-linux from the source code\&.
