.TH "admin" 3 "Wed Sep 17 2014" "Version 0.0.0" "admin-linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
admin \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAdminError\fP"
.br
.RI "\fIadmin error \fP"
.ti -1c
.RI "class \fBshell\fP"
.br
.RI "\fILinux shell tools\&. \fP"
.ti -1c
.RI "class \fBbuild\fP"
.br
.RI "\fIBuild tools\&. \fP"
.ti -1c
.RI "class \fBwww\fP"
.br
.RI "\fIWWW (Internet) tools\&. \fP"
.ti -1c
.RI "class \fBConfigFile\fP"
.br
.RI "\fIConfiguration file\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBupdate_seq_type\fP"
.br
.RI "\fIUpdate type of all elements in specific sequence\&. \fP"
.ti -1c
.RI "def \fB_setup\fP"
.br
.ti -1c
.RI "def \fB_usage\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBoption\fP = sys\&.argv[1]"
.br
.ti -1c
.RI "list \fBapp\fP = sys\&.argv[2]"
.br
.ti -1c
.RI "list \fBaddr\fP = sys\&.argv[3]"
.br
.ti -1c
.RI "list \fBupstream\fP = sys\&.argv[3]"
.br
.ti -1c
.RI "list \fBproject_path\fP = sys\&.argv[2]"
.br
.ti -1c
.RI "tuple \fBtest_app\fP = os\&.path\&.realpath('\fB_setup\fP/hello_uwsgi_app\&.py')"
.br
.ti -1c
.RI "string \fBtest_addr\fP = ':8000'"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def admin\&._setup (quick = \fCFalse\fP)\fC [private]\fP"

.PP
.nf
Setup Linux.

@param quick True if quick setup.
@todo Git under Proxy

.fi
.PP
 
.PP
Definition at line 719 of file admin\&.py\&.
.SS "def admin\&._usage ()\fC [private]\fP"

.PP
Definition at line 931 of file admin\&.py\&.
.SS "def admin\&.update_seq_type (seq, typename)"

.PP
Update type of all elements in specific sequence\&. 
.PP
\fBParameters:\fP
.RS 4
\fIseq\fP (mutable) sequence to be update 
.br
\fItypename\fP target type name 
.RE
.PP

.PP
Definition at line 57 of file admin\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "list admin\&.addr = sys\&.argv[3]"

.PP
Definition at line 949 of file admin\&.py\&.
.SS "list admin\&.app = sys\&.argv[2]"

.PP
Definition at line 948 of file admin\&.py\&.
.SS "list admin\&.option = sys\&.argv[1]"

.PP
Definition at line 939 of file admin\&.py\&.
.SS "list admin\&.project_path = sys\&.argv[2]"

.PP
Definition at line 978 of file admin\&.py\&.
.SS "string admin\&.test_addr = ':8000'"

.PP
Definition at line 987 of file admin\&.py\&.
.SS "tuple admin\&.test_app = os\&.path\&.realpath('\fB_setup\fP/hello_uwsgi_app\&.py')"

.PP
Definition at line 986 of file admin\&.py\&.
.SS "list admin\&.upstream = sys\&.argv[3]"

.PP
Definition at line 964 of file admin\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for admin-linux from the source code\&.
