.TH "admin.AdminTestCase" 3 "Tue Sep 9 2014" "Version 0.0.0" "admin-linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
admin.AdminTestCase \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsetUp\fP"
.br
.ti -1c
.RI "def \fBtearDown\fP"
.br
.ti -1c
.RI "def \fBtest_update_seq_type\fP"
.br
.ti -1c
.RI "def \fBtest_decode_version\fP"
.br
.ti -1c
.RI "def \fBtest_match_version\fP"
.br
.ti -1c
.RI "def \fBtest_read_lines\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBversion_info\fP"
.br
.ti -1c
.RI "\fBversion_prefix\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Test Case of Admin.

.fi
.PP
 
.PP
Definition at line 244 of file __init__\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def admin\&.AdminTestCase\&.setUp (self)"

.PP
Definition at line 247 of file __init__\&.py\&.
.SS "def admin\&.AdminTestCase\&.tearDown (self)"

.PP
Definition at line 252 of file __init__\&.py\&.
.SS "def admin\&.AdminTestCase\&.test_decode_version (self)"

.PP
Definition at line 263 of file __init__\&.py\&.
.SS "def admin\&.AdminTestCase\&.test_match_version (self)"

.PP
Definition at line 271 of file __init__\&.py\&.
.SS "def admin\&.AdminTestCase\&.test_read_lines (self)"

.PP
Definition at line 294 of file __init__\&.py\&.
.SS "def admin\&.AdminTestCase\&.test_update_seq_type (self)"

.PP
Definition at line 256 of file __init__\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "admin\&.AdminTestCase\&.version_info"

.PP
Definition at line 248 of file __init__\&.py\&.
.SS "admin\&.AdminTestCase\&.version_prefix"

.PP
Definition at line 249 of file __init__\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for admin-linux from the source code\&.
