.TH "admin.project.Project" 3 "Wed Sep 3 2014" "Version 0.0.0" "admin-linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
admin.project.Project \- 
.PP
\fBProject\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fICreate an instance of \fBProject\fP\&. \fP"
.ti -1c
.RI "def \fBuwsgi\fP"
.br
.ti -1c
.RI "def \fBdjango\fP"
.br
.ti -1c
.RI "def \fBdoxygen\fP"
.br
.RI "\fIGenerate documentation for codes under Git by Doxygen\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlang\fP"
.br
.ti -1c
.RI "\fBpath\fP"
.br
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBbrief\fP"
.br
.ti -1c
.RI "\fBversion_info\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fB_build_dir\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBProject\fP\&. 


.SS "Usage"
.PP
.PP
.nf
\fC
      import admin
      import \fBadmin\&.project\fP\fP
.fi
.PP
.PP
.PP
.nf
\fC      proj = \fBadmin\&.project\&.Project\fP(lang=['python'])
      try:
          # Setup uWSGI server
          proj\&.uwsgi()\fP
.fi
.PP
.PP
.PP
.nf
\fC          # Setup Django
          proj\&.django()\fP
.fi
.PP
.PP
.PP
.nf
\fC          # Generate documentation
          proj\&.doxygen()
      except subprocess\&.CalledProcessError as e:
          \fBadmin\&.error\fP('error')
      except IOError as e:
          \fBadmin\&.error\fP('error')
  \fP
.fi
.PP
 
.PP
Definition at line 56 of file project\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def admin\&.project\&.Project\&.__init__ (self, lang, build_dir = \fC'build'\fP, default_version = \fC'0\&.0\&.0'\fP)"

.PP
Create an instance of \fBProject\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlang\fP programming language (python, c, java, cpp) 
.br
\fIbuild_dir\fP building directory 
.br
\fIdefault_version\fP default version string 
.RE
.PP

.PP
Definition at line 62 of file project\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def admin\&.project\&.Project\&.django (self, site = \fC'mysite'\fP, nginx = \fCNone\fP, run = \fCFalse\fP)"

.PP
Definition at line 150 of file project\&.py\&.
.SS "def admin\&.project\&.Project\&.doxygen (self, doxyfile = \fC'Doxyfile'\fP)"

.PP
Generate documentation for codes under Git by Doxygen\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdoxyfile\fP name of Doxygen configuration file 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIsubprocess\&.CalledProcessError\fP - from \fCdoxygen\fP 
.br
\fIIOError\fP - configuration file written error 
.RE
.PP

.PP
Definition at line 174 of file project\&.py\&.
.SS "def admin\&.project\&.Project\&.uwsgi (self, wsgi_file = \fC'_setup/uwsgi_app\&.py'\fP, django = \fCNone\fP, nginx = \fCNone\fP, run = \fCFalse\fP)"

.PP
Definition at line 104 of file project\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "admin\&.project\&.Project\&._build_dir\fC [private]\fP"

.PP
Definition at line 66 of file project\&.py\&.
.SS "admin\&.project\&.Project\&.brief"

.PP
Definition at line 70 of file project\&.py\&.
.SS "admin\&.project\&.Project\&.lang"

.PP
Definition at line 63 of file project\&.py\&.
.SS "admin\&.project\&.Project\&.name"

.PP
Definition at line 65 of file project\&.py\&.
.SS "admin\&.project\&.Project\&.path"

.PP
Definition at line 64 of file project\&.py\&.
.SS "admin\&.project\&.Project\&.version_info"

.PP
Definition at line 79 of file project\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for admin-linux from the source code\&.
