.TH "admin.AdminTestCase" 3 "Wed Aug 27 2014" "Version 0.0.0" "admin-linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
admin.AdminTestCase \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsetUp\fP"
.br
.ti -1c
.RI "def \fBtearDown\fP"
.br
.ti -1c
.RI "def \fBtest_update_seq_type\fP"
.br
.ti -1c
.RI "def \fBtest_decode_version\fP"
.br
.ti -1c
.RI "def \fBtest_match_version\fP"
.br
.ti -1c
.RI "def \fBtest_read_lines\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBversion_info\fP"
.br
.ti -1c
.RI "\fBversion_prefix\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Test Case of Admin.

.fi
.PP
 
.PP
Definition at line 208 of file __init__\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def admin\&.AdminTestCase\&.setUp (self)"

.PP
Definition at line 211 of file __init__\&.py\&.
.SS "def admin\&.AdminTestCase\&.tearDown (self)"

.PP
Definition at line 216 of file __init__\&.py\&.
.SS "def admin\&.AdminTestCase\&.test_decode_version (self)"

.PP
Definition at line 227 of file __init__\&.py\&.
.SS "def admin\&.AdminTestCase\&.test_match_version (self)"

.PP
Definition at line 235 of file __init__\&.py\&.
.SS "def admin\&.AdminTestCase\&.test_read_lines (self)"

.PP
Definition at line 258 of file __init__\&.py\&.
.SS "def admin\&.AdminTestCase\&.test_update_seq_type (self)"

.PP
Definition at line 220 of file __init__\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "admin\&.AdminTestCase\&.version_info"

.PP
Definition at line 212 of file __init__\&.py\&.
.SS "admin\&.AdminTestCase\&.version_prefix"

.PP
Definition at line 213 of file __init__\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for admin-linux from the source code\&.
