.TH "_cookbook/context_manager.py" 3 "Wed Sep 17 2014" "Version 0.0.0" "admin-linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_cookbook/context_manager.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_cookbook\&.context_manager\&.MyContextManagerWithDecorator\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fB_cookbook\&.context_manager\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fB_cookbook\&.context_manager\&.opening\fP"
.br
.ti -1c
.RI "def \fB_cookbook\&.context_manager\&.closing\fP"
.br
.ti -1c
.RI "def \fB_cookbook\&.context_manager\&.test\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for admin-linux from the source code\&.
