.TH "_cookbook/format.py" 3 "Wed Sep 17 2014" "Version 0.0.0" "admin-linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_cookbook/format.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fB_cookbook\&.format\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fB_cookbook\&.format\&.test_float_format\fP"
.br
.ti -1c
.RI "def \fB_cookbook\&.format\&.test_int_format\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for admin-linux from the source code\&.
