.TH "hello_uwsgi_app" 3 "Wed Sep 17 2014" "Version 0.0.0" "admin-linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hello_uwsgi_app \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBapplication\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def hello_uwsgi_app\&.application (env, start_response)"

.PP
Definition at line 22 of file hello_uwsgi_app\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for admin-linux from the source code\&.
