.TH "_cookbook/loop.py" 3 "Wed Sep 17 2014" "Version 0.0.0" "admin-linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_cookbook/loop.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_cookbook\&.loop\&.MyIterator\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fB_cookbook\&.loop\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fB_cookbook\&.loop\&.my_generator\fP"
.br
.ti -1c
.RI "def \fB_cookbook\&.loop\&.test_filter\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fB_cookbook\&.loop\&.seq\fP = []"
.br
.ti -1c
.RI "list \fB_cookbook\&.loop\&.words\fP = []"
.br
.ti -1c
.RI "dictionary \fB_cookbook\&.loop\&.mydict\fP = {}"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for admin-linux from the source code\&.
