.TH "_cookbook/my_pyunit.py" 3 "Wed Sep 17 2014" "Version 0.0.0" "admin-linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_cookbook/my_pyunit.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_cookbook\&.my_pyunit\&.TestCase\fP"
.br
.ti -1c
.RI "class \fB_cookbook\&.my_pyunit\&.TestSuite\fP"
.br
.ti -1c
.RI "class \fB_cookbook\&.my_pyunit\&.MyPyUnitTest\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fB_cookbook\&.my_pyunit\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fB_cookbook\&.my_pyunit\&._test_suite\fP = []"
.br
.ti -1c
.RI "tuple \fB_cookbook\&.my_pyunit\&.suite\fP = TestSuite()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for admin-linux from the source code\&.
