.TH "_cookbook/network.py" 3 "Wed Sep 17 2014" "Version 0.0.0" "admin-linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_cookbook/network.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_cookbook\&.network\&.MyTCPServer\fP"
.br
.ti -1c
.RI "class \fB_cookbook\&.network\&.MyUDPServer\fP"
.br
.ti -1c
.RI "class \fB_cookbook\&.network\&.MyTCPHandler\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fB_cookbook\&.network\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fB_cookbook\&.network\&._eintr_retry\fP"
.br
.ti -1c
.RI "def \fB_cookbook\&.network\&.tcp_client\fP"
.br
.ti -1c
.RI "def \fB_cookbook\&.network\&.udp_client\fP"
.br
.ti -1c
.RI "def \fB_cookbook\&.network\&.tcp_server\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fB_cookbook\&.network\&.srv\fP = MyTCPServer(('', 10000))"
.br
.ti -1c
.RI "tuple \fB_cookbook\&.network\&.srv_addr\fP = ('localhost', 10000)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for admin-linux from the source code\&.
