.TH "project.Project" 3 "Wed Sep 17 2014" "Version 0.0.0" "admin-linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
project.Project \- 
.PP
\fBProject\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fICreate an instance of \fBProject\fP\&. \fP"
.ti -1c
.RI "def \fBdoxygen\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtypes\fP"
.br
.ti -1c
.RI "\fBpath\fP"
.br
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBversion_info\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fB_uwsgi_ini\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "tuple \fB_setup_dir\fP = os\&.path\&.realpath('_setup')"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBProject\fP\&. 


.SS "Usage"
.PP
.PP
.nf
\fC
      import admin
      import admin\&.project\fP
.fi
.PP
.PP
.PP
.nf
\fC      try:
          proj = admin\&.project\&.Project(types=['python'], name='test')
      except os\&.error as e:
          admin\&.error(e)\fP
.fi
.PP
.PP
.PP
.nf
\fC      # Generate documentation
      try:
          proj\&.doxygen()
      except subprocess\&.CalledProcessError as e:
          admin\&.error(e)
      except IOError as e:
          admin\&.error(e)
  \fP
.fi
.PP
 
.PP
Definition at line 55 of file project\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def project\&.Project\&.__init__ (self, types, name = \fC'test'\fP)"

.PP
Create an instance of \fBProject\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fItypes\fP project types (python, django, c, java, cpp) 
.br
\fIname\fP project name 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIos\&.error\fP 
.RE
.PP

.PP
Definition at line 63 of file project\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def project\&.Project\&.doxygen (self, doxyfile = \fC'Doxyfile'\fP)"

.PP
Definition at line 93 of file project\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "tuple project\&.Project\&._setup_dir = os\&.path\&.realpath('_setup')\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 56 of file project\&.py\&.
.SS "project\&.Project\&._uwsgi_ini\fC [private]\fP"

.PP
Definition at line 68 of file project\&.py\&.
.SS "project\&.Project\&.name"

.PP
Definition at line 66 of file project\&.py\&.
.SS "project\&.Project\&.path"

.PP
Definition at line 65 of file project\&.py\&.
.SS "project\&.Project\&.types"

.PP
Definition at line 64 of file project\&.py\&.
.SS "project\&.Project\&.version_info"

.PP
Definition at line 77 of file project\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for admin-linux from the source code\&.
