.TH "_cookbook/thread/semaphore.py" 3 "Wed Sep 17 2014" "Version 0.0.0" "admin-linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_cookbook/thread/semaphore.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_cookbook\&.thread\&.semaphore\&.Producer\fP"
.br
.ti -1c
.RI "class \fB_cookbook\&.thread\&.semaphore\&.Cusumer\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fB_cookbook\&.thread\&.semaphore\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fB_cookbook\&.thread\&.semaphore\&.test_semaphore\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fB_cookbook\&.thread\&.semaphore\&.share\fP = []"
.br
.ti -1c
.RI "int \fB_cookbook\&.thread\&.semaphore\&.MAX_COUNTS\fP = 5"
.br
.ti -1c
.RI "tuple \fB_cookbook\&.thread\&.semaphore\&.semaphore\fP = threading\&.BoundedSemaphore(MAX_COUNTS)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for admin-linux from the source code\&.
