.TH "_cookbook/sort.py" 3 "Wed Sep 17 2014" "Version 0.0.0" "admin-linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_cookbook/sort.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_cookbook\&.sort\&.App\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fB_cookbook\&.sort\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fB_cookbook\&.sort\&.d\fP"
.br
.ti -1c
.RI "list \fB_cookbook\&.sort\&.apps\fP = [App(1), App(2), App(3)]"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for admin-linux from the source code\&.
